<?xml version="1.0" encoding="utf-8"?><Database Name="QLBDS" Class="dtbbdsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=hung\sqlexpress;Initial Catalog=QLBDS;Integrated Security=True" SettingsObjectName="testDEVE.Properties.Settings" SettingsPropertyName="QLBDSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BatDongSan" Member="BatDongSans">
    <Type Name="BatDongSan">
      <Column Name="bdsid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="loaiid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="khid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tinhtrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="dientich" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dongia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="masoqsdd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mota" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="hinhanh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="chieudai" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="chieurong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tenduong" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="sonha" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="quan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="BatDongSan_HopDongChuyenNhuong" Member="HopDongChuyenNhuongs" ThisKey="bdsid" OtherKey="bdsid" Type="HopDongChuyenNhuong" />
      <Association Name="BatDongSan_HopDongDatCoc" Member="HopDongDatCocs" ThisKey="bdsid" OtherKey="bdsid" Type="HopDongDatCoc" />
      <Association Name="BatDongSan_HopDongKyGui" Member="HopDongKyGuis" ThisKey="bdsid" OtherKey="bdsid" Type="HopDongKyGui" />
      <Association Name="KhachHang_BatDongSan" Member="KhachHang" ThisKey="khid" OtherKey="khid" Type="KhachHang" IsForeignKey="true" />
      <Association Name="LoaiBD_BatDongSan" Member="LoaiBD" ThisKey="loaiid" OtherKey="loaiid" Type="LoaiBD" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.YeuCauKhachHang" Member="YeuCauKhachHangs">
    <Type Name="YeuCauKhachHang">
      <Column Name="ycid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="loaiid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="khid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nvid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dientich" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="vitri" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="giatri" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="mota" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="KhachHang_YeuCauKhachHang" Member="KhachHang" ThisKey="khid" OtherKey="khid" Type="KhachHang" IsForeignKey="true" />
      <Association Name="LoaiBD_YeuCauKhachHang" Member="LoaiBD" ThisKey="loaiid" OtherKey="loaiid" Type="LoaiBD" IsForeignKey="true" />
      <Association Name="NhanVien_YeuCauKhachHang" Member="NhanVien" ThisKey="khid" OtherKey="nvid" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HopDongChuyenNhuong" Member="HopDongChuyenNhuongs">
    <Type Name="HopDongChuyenNhuong">
      <Column Name="cnid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nvid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="khid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bdsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="giatri" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ngaylap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="HopDongChuyenNhuong_HopDongDatCoc" Member="HopDongDatCocs" ThisKey="cnid" OtherKey="cnid" Type="HopDongDatCoc" />
      <Association Name="BatDongSan_HopDongChuyenNhuong" Member="BatDongSan" ThisKey="bdsid" OtherKey="bdsid" Type="BatDongSan" IsForeignKey="true" />
      <Association Name="KhachHang_HopDongChuyenNhuong" Member="KhachHang" ThisKey="khid" OtherKey="khid" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HopDongChuyenNhuong" Member="NhanVien" ThisKey="nvid" OtherKey="nvid" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HopDongDatCoc" Member="HopDongDatCocs">
    <Type Name="HopDongDatCoc">
      <Column Name="dcid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nvid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="khid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bdsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cnid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngaylaphd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="sodot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pttt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="giatri" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tinhtrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BatDongSan_HopDongDatCoc" Member="BatDongSan" ThisKey="bdsid" OtherKey="bdsid" Type="BatDongSan" IsForeignKey="true" />
      <Association Name="HopDongChuyenNhuong_HopDongDatCoc" Member="HopDongChuyenNhuong" ThisKey="cnid" OtherKey="cnid" Type="HopDongChuyenNhuong" IsForeignKey="true" />
      <Association Name="KhachHang_HopDongDatCoc" Member="KhachHang" ThisKey="khid" OtherKey="khid" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HopDongDatCoc" Member="NhanVien" ThisKey="nvid" OtherKey="nvid" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HopDongKyGui" Member="HopDongKyGuis">
    <Type Name="HopDongKyGui">
      <Column Name="kgid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nvid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="khid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bdsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="giatri" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="chiphidv" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ngaybd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngaykt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="BatDongSan_HopDongKyGui" Member="BatDongSan" ThisKey="bdsid" OtherKey="bdsid" Type="BatDongSan" IsForeignKey="true" />
      <Association Name="KhachHang_HopDongKyGui" Member="KhachHang" ThisKey="khid" OtherKey="khid" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HopDongKyGui" Member="NhanVien" ThisKey="nvid" OtherKey="nvid" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="khid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cmnd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="sdt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="loaikh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mota" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="nvid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_BatDongSan" Member="BatDongSans" ThisKey="khid" OtherKey="khid" Type="BatDongSan" />
      <Association Name="KhachHang_YeuCauKhachHang" Member="YeuCauKhachHangs" ThisKey="khid" OtherKey="khid" Type="YeuCauKhachHang" />
      <Association Name="KhachHang_HopDongChuyenNhuong" Member="HopDongChuyenNhuongs" ThisKey="khid" OtherKey="khid" Type="HopDongChuyenNhuong" />
      <Association Name="KhachHang_HopDongDatCoc" Member="HopDongDatCocs" ThisKey="khid" OtherKey="khid" Type="HopDongDatCoc" />
      <Association Name="KhachHang_HopDongKyGui" Member="HopDongKyGuis" ThisKey="khid" OtherKey="khid" Type="HopDongKyGui" />
      <Association Name="NhanVien_KhachHang" Member="NhanVien" ThisKey="nvid" OtherKey="nvid" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiBDS" Member="LoaiBDs">
    <Type Name="LoaiBD">
      <Column Name="loaiid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenloai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="LoaiBD_BatDongSan" Member="BatDongSans" ThisKey="loaiid" OtherKey="loaiid" Type="BatDongSan" />
      <Association Name="LoaiBD_YeuCauKhachHang" Member="YeuCauKhachHangs" ThisKey="loaiid" OtherKey="loaiid" Type="YeuCauKhachHang" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="nvid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="taikhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tennv" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sdt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="doanhthu" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="quyen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="hinh" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="NhanVien_YeuCauKhachHang" Member="YeuCauKhachHangs" ThisKey="nvid" OtherKey="khid" Type="YeuCauKhachHang" />
      <Association Name="NhanVien_HopDongChuyenNhuong" Member="HopDongChuyenNhuongs" ThisKey="nvid" OtherKey="nvid" Type="HopDongChuyenNhuong" />
      <Association Name="NhanVien_HopDongDatCoc" Member="HopDongDatCocs" ThisKey="nvid" OtherKey="nvid" Type="HopDongDatCoc" />
      <Association Name="NhanVien_HopDongKyGui" Member="HopDongKyGuis" ThisKey="nvid" OtherKey="nvid" Type="HopDongKyGui" />
      <Association Name="NhanVien_KhachHang" Member="KhachHangs" ThisKey="nvid" OtherKey="nvid" Type="KhachHang" />
    </Type>
  </Table>
</Database>