#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDEVE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBDS")]
	public partial class dtbbdsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBatDongSan(BatDongSan instance);
    partial void UpdateBatDongSan(BatDongSan instance);
    partial void DeleteBatDongSan(BatDongSan instance);
    partial void InsertYeuCauKhachHang(YeuCauKhachHang instance);
    partial void UpdateYeuCauKhachHang(YeuCauKhachHang instance);
    partial void DeleteYeuCauKhachHang(YeuCauKhachHang instance);
    partial void InsertHopDongChuyenNhuong(HopDongChuyenNhuong instance);
    partial void UpdateHopDongChuyenNhuong(HopDongChuyenNhuong instance);
    partial void DeleteHopDongChuyenNhuong(HopDongChuyenNhuong instance);
    partial void InsertHopDongDatCoc(HopDongDatCoc instance);
    partial void UpdateHopDongDatCoc(HopDongDatCoc instance);
    partial void DeleteHopDongDatCoc(HopDongDatCoc instance);
    partial void InsertHopDongKyGui(HopDongKyGui instance);
    partial void UpdateHopDongKyGui(HopDongKyGui instance);
    partial void DeleteHopDongKyGui(HopDongKyGui instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiBD(LoaiBD instance);
    partial void UpdateLoaiBD(LoaiBD instance);
    partial void DeleteLoaiBD(LoaiBD instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    #endregion
		
		public dtbbdsDataContext() : 
				base(global::testDEVE.Properties.Settings.Default.QLBDSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dtbbdsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dtbbdsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dtbbdsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dtbbdsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BatDongSan> BatDongSans
		{
			get
			{
				return this.GetTable<BatDongSan>();
			}
		}
		
		public System.Data.Linq.Table<YeuCauKhachHang> YeuCauKhachHangs
		{
			get
			{
				return this.GetTable<YeuCauKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<HopDongChuyenNhuong> HopDongChuyenNhuongs
		{
			get
			{
				return this.GetTable<HopDongChuyenNhuong>();
			}
		}
		
		public System.Data.Linq.Table<HopDongDatCoc> HopDongDatCocs
		{
			get
			{
				return this.GetTable<HopDongDatCoc>();
			}
		}
		
		public System.Data.Linq.Table<HopDongKyGui> HopDongKyGuis
		{
			get
			{
				return this.GetTable<HopDongKyGui>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiBD> LoaiBDs
		{
			get
			{
				return this.GetTable<LoaiBD>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BatDongSan")]
	public partial class BatDongSan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _bdsid;
		
		private int _loaiid;
		
		private int _khid;
		
		private System.Nullable<bool> _tinhtrang;
		
		private System.Nullable<double> _dientich;
		
		private System.Nullable<double> _dongia;
		
		private string _masoqsdd;
		
		private string _mota;
		
		private System.Data.Linq.Binary _hinhanh;
		
		private System.Nullable<double> _chieudai;
		
		private System.Nullable<double> _chieurong;
		
		private string _tenduong;
		
		private string _sonha;
		
		private string _quan;
		
		private EntitySet<HopDongChuyenNhuong> _HopDongChuyenNhuongs;
		
		private EntitySet<HopDongDatCoc> _HopDongDatCocs;
		
		private EntitySet<HopDongKyGui> _HopDongKyGuis;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<LoaiBD> _LoaiBD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbdsidChanging(int value);
    partial void OnbdsidChanged();
    partial void OnloaiidChanging(int value);
    partial void OnloaiidChanged();
    partial void OnkhidChanging(int value);
    partial void OnkhidChanged();
    partial void OntinhtrangChanging(System.Nullable<bool> value);
    partial void OntinhtrangChanged();
    partial void OndientichChanging(System.Nullable<double> value);
    partial void OndientichChanged();
    partial void OndongiaChanging(System.Nullable<double> value);
    partial void OndongiaChanged();
    partial void OnmasoqsddChanging(string value);
    partial void OnmasoqsddChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OnhinhanhChanging(System.Data.Linq.Binary value);
    partial void OnhinhanhChanged();
    partial void OnchieudaiChanging(System.Nullable<double> value);
    partial void OnchieudaiChanged();
    partial void OnchieurongChanging(System.Nullable<double> value);
    partial void OnchieurongChanged();
    partial void OntenduongChanging(string value);
    partial void OntenduongChanged();
    partial void OnsonhaChanging(string value);
    partial void OnsonhaChanged();
    partial void OnquanChanging(string value);
    partial void OnquanChanged();
    #endregion
		
		public BatDongSan()
		{
			this._HopDongChuyenNhuongs = new EntitySet<HopDongChuyenNhuong>(new Action<HopDongChuyenNhuong>(this.attach_HopDongChuyenNhuongs), new Action<HopDongChuyenNhuong>(this.detach_HopDongChuyenNhuongs));
			this._HopDongDatCocs = new EntitySet<HopDongDatCoc>(new Action<HopDongDatCoc>(this.attach_HopDongDatCocs), new Action<HopDongDatCoc>(this.detach_HopDongDatCocs));
			this._HopDongKyGuis = new EntitySet<HopDongKyGui>(new Action<HopDongKyGui>(this.attach_HopDongKyGuis), new Action<HopDongKyGui>(this.detach_HopDongKyGuis));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._LoaiBD = default(EntityRef<LoaiBD>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bdsid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int bdsid
		{
			get
			{
				return this._bdsid;
			}
			set
			{
				if ((this._bdsid != value))
				{
					this.OnbdsidChanging(value);
					this.SendPropertyChanging();
					this._bdsid = value;
					this.SendPropertyChanged("bdsid");
					this.OnbdsidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiid", DbType="Int NOT NULL")]
		public int loaiid
		{
			get
			{
				return this._loaiid;
			}
			set
			{
				if ((this._loaiid != value))
				{
					if (this._LoaiBD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnloaiidChanging(value);
					this.SendPropertyChanging();
					this._loaiid = value;
					this.SendPropertyChanged("loaiid");
					this.OnloaiidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khid", DbType="Int NOT NULL")]
		public int khid
		{
			get
			{
				return this._khid;
			}
			set
			{
				if ((this._khid != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhidChanging(value);
					this.SendPropertyChanging();
					this._khid = value;
					this.SendPropertyChanged("khid");
					this.OnkhidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="Bit")]
		public System.Nullable<bool> tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dientich", DbType="Float")]
		public System.Nullable<double> dientich
		{
			get
			{
				return this._dientich;
			}
			set
			{
				if ((this._dientich != value))
				{
					this.OndientichChanging(value);
					this.SendPropertyChanging();
					this._dientich = value;
					this.SendPropertyChanged("dientich");
					this.OndientichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="Float")]
		public System.Nullable<double> dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this.OndongiaChanging(value);
					this.SendPropertyChanging();
					this._dongia = value;
					this.SendPropertyChanged("dongia");
					this.OndongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masoqsdd", DbType="VarChar(50)")]
		public string masoqsdd
		{
			get
			{
				return this._masoqsdd;
			}
			set
			{
				if ((this._masoqsdd != value))
				{
					this.OnmasoqsddChanging(value);
					this.SendPropertyChanging();
					this._masoqsdd = value;
					this.SendPropertyChanged("masoqsdd");
					this.OnmasoqsddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="VarChar(100)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this.OnhinhanhChanging(value);
					this.SendPropertyChanging();
					this._hinhanh = value;
					this.SendPropertyChanged("hinhanh");
					this.OnhinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chieudai", DbType="Float")]
		public System.Nullable<double> chieudai
		{
			get
			{
				return this._chieudai;
			}
			set
			{
				if ((this._chieudai != value))
				{
					this.OnchieudaiChanging(value);
					this.SendPropertyChanging();
					this._chieudai = value;
					this.SendPropertyChanged("chieudai");
					this.OnchieudaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chieurong", DbType="Float")]
		public System.Nullable<double> chieurong
		{
			get
			{
				return this._chieurong;
			}
			set
			{
				if ((this._chieurong != value))
				{
					this.OnchieurongChanging(value);
					this.SendPropertyChanging();
					this._chieurong = value;
					this.SendPropertyChanged("chieurong");
					this.OnchieurongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenduong", DbType="VarChar(100)")]
		public string tenduong
		{
			get
			{
				return this._tenduong;
			}
			set
			{
				if ((this._tenduong != value))
				{
					this.OntenduongChanging(value);
					this.SendPropertyChanging();
					this._tenduong = value;
					this.SendPropertyChanged("tenduong");
					this.OntenduongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonha", DbType="VarChar(10)")]
		public string sonha
		{
			get
			{
				return this._sonha;
			}
			set
			{
				if ((this._sonha != value))
				{
					this.OnsonhaChanging(value);
					this.SendPropertyChanging();
					this._sonha = value;
					this.SendPropertyChanged("sonha");
					this.OnsonhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quan", DbType="VarChar(50)")]
		public string quan
		{
			get
			{
				return this._quan;
			}
			set
			{
				if ((this._quan != value))
				{
					this.OnquanChanging(value);
					this.SendPropertyChanging();
					this._quan = value;
					this.SendPropertyChanged("quan");
					this.OnquanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BatDongSan_HopDongChuyenNhuong", Storage="_HopDongChuyenNhuongs", ThisKey="bdsid", OtherKey="bdsid")]
		public EntitySet<HopDongChuyenNhuong> HopDongChuyenNhuongs
		{
			get
			{
				return this._HopDongChuyenNhuongs;
			}
			set
			{
				this._HopDongChuyenNhuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BatDongSan_HopDongDatCoc", Storage="_HopDongDatCocs", ThisKey="bdsid", OtherKey="bdsid")]
		public EntitySet<HopDongDatCoc> HopDongDatCocs
		{
			get
			{
				return this._HopDongDatCocs;
			}
			set
			{
				this._HopDongDatCocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BatDongSan_HopDongKyGui", Storage="_HopDongKyGuis", ThisKey="bdsid", OtherKey="bdsid")]
		public EntitySet<HopDongKyGui> HopDongKyGuis
		{
			get
			{
				return this._HopDongKyGuis;
			}
			set
			{
				this._HopDongKyGuis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_BatDongSan", Storage="_KhachHang", ThisKey="khid", OtherKey="khid", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.BatDongSans.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.BatDongSans.Add(this);
						this._khid = value.khid;
					}
					else
					{
						this._khid = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiBD_BatDongSan", Storage="_LoaiBD", ThisKey="loaiid", OtherKey="loaiid", IsForeignKey=true)]
		public LoaiBD LoaiBD
		{
			get
			{
				return this._LoaiBD.Entity;
			}
			set
			{
				LoaiBD previousValue = this._LoaiBD.Entity;
				if (((previousValue != value) 
							|| (this._LoaiBD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiBD.Entity = null;
						previousValue.BatDongSans.Remove(this);
					}
					this._LoaiBD.Entity = value;
					if ((value != null))
					{
						value.BatDongSans.Add(this);
						this._loaiid = value.loaiid;
					}
					else
					{
						this._loaiid = default(int);
					}
					this.SendPropertyChanged("LoaiBD");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HopDongChuyenNhuongs(HopDongChuyenNhuong entity)
		{
			this.SendPropertyChanging();
			entity.BatDongSan = this;
		}
		
		private void detach_HopDongChuyenNhuongs(HopDongChuyenNhuong entity)
		{
			this.SendPropertyChanging();
			entity.BatDongSan = null;
		}
		
		private void attach_HopDongDatCocs(HopDongDatCoc entity)
		{
			this.SendPropertyChanging();
			entity.BatDongSan = this;
		}
		
		private void detach_HopDongDatCocs(HopDongDatCoc entity)
		{
			this.SendPropertyChanging();
			entity.BatDongSan = null;
		}
		
		private void attach_HopDongKyGuis(HopDongKyGui entity)
		{
			this.SendPropertyChanging();
			entity.BatDongSan = this;
		}
		
		private void detach_HopDongKyGuis(HopDongKyGui entity)
		{
			this.SendPropertyChanging();
			entity.BatDongSan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YeuCauKhachHang")]
	public partial class YeuCauKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ycid;
		
		private int _loaiid;
		
		private int _khid;
		
		private int _nvid;
		
		private System.Nullable<double> _dientich;
		
		private string _vitri;
		
		private System.Nullable<double> _giatri;
		
		private string _mota;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<LoaiBD> _LoaiBD;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnycidChanging(int value);
    partial void OnycidChanged();
    partial void OnloaiidChanging(int value);
    partial void OnloaiidChanged();
    partial void OnkhidChanging(int value);
    partial void OnkhidChanged();
    partial void OnnvidChanging(int value);
    partial void OnnvidChanged();
    partial void OndientichChanging(System.Nullable<double> value);
    partial void OndientichChanged();
    partial void OnvitriChanging(string value);
    partial void OnvitriChanged();
    partial void OngiatriChanging(System.Nullable<double> value);
    partial void OngiatriChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    #endregion
		
		public YeuCauKhachHang()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._LoaiBD = default(EntityRef<LoaiBD>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ycid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ycid
		{
			get
			{
				return this._ycid;
			}
			set
			{
				if ((this._ycid != value))
				{
					this.OnycidChanging(value);
					this.SendPropertyChanging();
					this._ycid = value;
					this.SendPropertyChanged("ycid");
					this.OnycidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiid", DbType="Int NOT NULL")]
		public int loaiid
		{
			get
			{
				return this._loaiid;
			}
			set
			{
				if ((this._loaiid != value))
				{
					if (this._LoaiBD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnloaiidChanging(value);
					this.SendPropertyChanging();
					this._loaiid = value;
					this.SendPropertyChanged("loaiid");
					this.OnloaiidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khid", DbType="Int NOT NULL")]
		public int khid
		{
			get
			{
				return this._khid;
			}
			set
			{
				if ((this._khid != value))
				{
					if ((this._KhachHang.HasLoadedOrAssignedValue || this._NhanVien.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhidChanging(value);
					this.SendPropertyChanging();
					this._khid = value;
					this.SendPropertyChanged("khid");
					this.OnkhidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvid", DbType="Int NOT NULL")]
		public int nvid
		{
			get
			{
				return this._nvid;
			}
			set
			{
				if ((this._nvid != value))
				{
					this.OnnvidChanging(value);
					this.SendPropertyChanging();
					this._nvid = value;
					this.SendPropertyChanged("nvid");
					this.OnnvidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dientich", DbType="Float")]
		public System.Nullable<double> dientich
		{
			get
			{
				return this._dientich;
			}
			set
			{
				if ((this._dientich != value))
				{
					this.OndientichChanging(value);
					this.SendPropertyChanging();
					this._dientich = value;
					this.SendPropertyChanged("dientich");
					this.OndientichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vitri", DbType="VarChar(50)")]
		public string vitri
		{
			get
			{
				return this._vitri;
			}
			set
			{
				if ((this._vitri != value))
				{
					this.OnvitriChanging(value);
					this.SendPropertyChanging();
					this._vitri = value;
					this.SendPropertyChanged("vitri");
					this.OnvitriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatri", DbType="Float")]
		public System.Nullable<double> giatri
		{
			get
			{
				return this._giatri;
			}
			set
			{
				if ((this._giatri != value))
				{
					this.OngiatriChanging(value);
					this.SendPropertyChanging();
					this._giatri = value;
					this.SendPropertyChanged("giatri");
					this.OngiatriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="VarChar(100)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_YeuCauKhachHang", Storage="_KhachHang", ThisKey="khid", OtherKey="khid", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.YeuCauKhachHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.YeuCauKhachHangs.Add(this);
						this._khid = value.khid;
					}
					else
					{
						this._khid = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiBD_YeuCauKhachHang", Storage="_LoaiBD", ThisKey="loaiid", OtherKey="loaiid", IsForeignKey=true)]
		public LoaiBD LoaiBD
		{
			get
			{
				return this._LoaiBD.Entity;
			}
			set
			{
				LoaiBD previousValue = this._LoaiBD.Entity;
				if (((previousValue != value) 
							|| (this._LoaiBD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiBD.Entity = null;
						previousValue.YeuCauKhachHangs.Remove(this);
					}
					this._LoaiBD.Entity = value;
					if ((value != null))
					{
						value.YeuCauKhachHangs.Add(this);
						this._loaiid = value.loaiid;
					}
					else
					{
						this._loaiid = default(int);
					}
					this.SendPropertyChanged("LoaiBD");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_YeuCauKhachHang", Storage="_NhanVien", ThisKey="khid", OtherKey="nvid", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.YeuCauKhachHangs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.YeuCauKhachHangs.Add(this);
						this._khid = value.nvid;
					}
					else
					{
						this._khid = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDongChuyenNhuong")]
	public partial class HopDongChuyenNhuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cnid;
		
		private int _nvid;
		
		private int _khid;
		
		private int _bdsid;
		
		private System.Nullable<double> _giatri;
		
		private System.Nullable<System.DateTime> _ngaylap;
		
		private EntitySet<HopDongDatCoc> _HopDongDatCocs;
		
		private EntityRef<BatDongSan> _BatDongSan;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncnidChanging(int value);
    partial void OncnidChanged();
    partial void OnnvidChanging(int value);
    partial void OnnvidChanged();
    partial void OnkhidChanging(int value);
    partial void OnkhidChanged();
    partial void OnbdsidChanging(int value);
    partial void OnbdsidChanged();
    partial void OngiatriChanging(System.Nullable<double> value);
    partial void OngiatriChanged();
    partial void OnngaylapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylapChanged();
    #endregion
		
		public HopDongChuyenNhuong()
		{
			this._HopDongDatCocs = new EntitySet<HopDongDatCoc>(new Action<HopDongDatCoc>(this.attach_HopDongDatCocs), new Action<HopDongDatCoc>(this.detach_HopDongDatCocs));
			this._BatDongSan = default(EntityRef<BatDongSan>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cnid
		{
			get
			{
				return this._cnid;
			}
			set
			{
				if ((this._cnid != value))
				{
					this.OncnidChanging(value);
					this.SendPropertyChanging();
					this._cnid = value;
					this.SendPropertyChanged("cnid");
					this.OncnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvid", DbType="Int NOT NULL")]
		public int nvid
		{
			get
			{
				return this._nvid;
			}
			set
			{
				if ((this._nvid != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnvidChanging(value);
					this.SendPropertyChanging();
					this._nvid = value;
					this.SendPropertyChanged("nvid");
					this.OnnvidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khid", DbType="Int NOT NULL")]
		public int khid
		{
			get
			{
				return this._khid;
			}
			set
			{
				if ((this._khid != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhidChanging(value);
					this.SendPropertyChanging();
					this._khid = value;
					this.SendPropertyChanged("khid");
					this.OnkhidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bdsid", DbType="Int NOT NULL")]
		public int bdsid
		{
			get
			{
				return this._bdsid;
			}
			set
			{
				if ((this._bdsid != value))
				{
					if (this._BatDongSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnbdsidChanging(value);
					this.SendPropertyChanging();
					this._bdsid = value;
					this.SendPropertyChanged("bdsid");
					this.OnbdsidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatri", DbType="Float")]
		public System.Nullable<double> giatri
		{
			get
			{
				return this._giatri;
			}
			set
			{
				if ((this._giatri != value))
				{
					this.OngiatriChanging(value);
					this.SendPropertyChanging();
					this._giatri = value;
					this.SendPropertyChanged("giatri");
					this.OngiatriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylap", DbType="Date")]
		public System.Nullable<System.DateTime> ngaylap
		{
			get
			{
				return this._ngaylap;
			}
			set
			{
				if ((this._ngaylap != value))
				{
					this.OnngaylapChanging(value);
					this.SendPropertyChanging();
					this._ngaylap = value;
					this.SendPropertyChanged("ngaylap");
					this.OnngaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDongChuyenNhuong_HopDongDatCoc", Storage="_HopDongDatCocs", ThisKey="cnid", OtherKey="cnid")]
		public EntitySet<HopDongDatCoc> HopDongDatCocs
		{
			get
			{
				return this._HopDongDatCocs;
			}
			set
			{
				this._HopDongDatCocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BatDongSan_HopDongChuyenNhuong", Storage="_BatDongSan", ThisKey="bdsid", OtherKey="bdsid", IsForeignKey=true)]
		public BatDongSan BatDongSan
		{
			get
			{
				return this._BatDongSan.Entity;
			}
			set
			{
				BatDongSan previousValue = this._BatDongSan.Entity;
				if (((previousValue != value) 
							|| (this._BatDongSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BatDongSan.Entity = null;
						previousValue.HopDongChuyenNhuongs.Remove(this);
					}
					this._BatDongSan.Entity = value;
					if ((value != null))
					{
						value.HopDongChuyenNhuongs.Add(this);
						this._bdsid = value.bdsid;
					}
					else
					{
						this._bdsid = default(int);
					}
					this.SendPropertyChanged("BatDongSan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HopDongChuyenNhuong", Storage="_KhachHang", ThisKey="khid", OtherKey="khid", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HopDongChuyenNhuongs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HopDongChuyenNhuongs.Add(this);
						this._khid = value.khid;
					}
					else
					{
						this._khid = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HopDongChuyenNhuong", Storage="_NhanVien", ThisKey="nvid", OtherKey="nvid", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HopDongChuyenNhuongs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HopDongChuyenNhuongs.Add(this);
						this._nvid = value.nvid;
					}
					else
					{
						this._nvid = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HopDongDatCocs(HopDongDatCoc entity)
		{
			this.SendPropertyChanging();
			entity.HopDongChuyenNhuong = this;
		}
		
		private void detach_HopDongDatCocs(HopDongDatCoc entity)
		{
			this.SendPropertyChanging();
			entity.HopDongChuyenNhuong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDongDatCoc")]
	public partial class HopDongDatCoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dcid;
		
		private int _nvid;
		
		private int _khid;
		
		private int _bdsid;
		
		private int _cnid;
		
		private System.Nullable<System.DateTime> _ngaylaphd;
		
		private System.Nullable<int> _sodot;
		
		private string _pttt;
		
		private System.Nullable<double> _giatri;
		
		private System.Nullable<int> _tinhtrang;
		
		private EntityRef<BatDongSan> _BatDongSan;
		
		private EntityRef<HopDongChuyenNhuong> _HopDongChuyenNhuong;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndcidChanging(int value);
    partial void OndcidChanged();
    partial void OnnvidChanging(int value);
    partial void OnnvidChanged();
    partial void OnkhidChanging(int value);
    partial void OnkhidChanged();
    partial void OnbdsidChanging(int value);
    partial void OnbdsidChanged();
    partial void OncnidChanging(int value);
    partial void OncnidChanged();
    partial void OnngaylaphdChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylaphdChanged();
    partial void OnsodotChanging(System.Nullable<int> value);
    partial void OnsodotChanged();
    partial void OnptttChanging(string value);
    partial void OnptttChanged();
    partial void OngiatriChanging(System.Nullable<double> value);
    partial void OngiatriChanged();
    partial void OntinhtrangChanging(System.Nullable<int> value);
    partial void OntinhtrangChanged();
    #endregion
		
		public HopDongDatCoc()
		{
			this._BatDongSan = default(EntityRef<BatDongSan>);
			this._HopDongChuyenNhuong = default(EntityRef<HopDongChuyenNhuong>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dcid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int dcid
		{
			get
			{
				return this._dcid;
			}
			set
			{
				if ((this._dcid != value))
				{
					this.OndcidChanging(value);
					this.SendPropertyChanging();
					this._dcid = value;
					this.SendPropertyChanged("dcid");
					this.OndcidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvid", DbType="Int NOT NULL")]
		public int nvid
		{
			get
			{
				return this._nvid;
			}
			set
			{
				if ((this._nvid != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnvidChanging(value);
					this.SendPropertyChanging();
					this._nvid = value;
					this.SendPropertyChanged("nvid");
					this.OnnvidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khid", DbType="Int NOT NULL")]
		public int khid
		{
			get
			{
				return this._khid;
			}
			set
			{
				if ((this._khid != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhidChanging(value);
					this.SendPropertyChanging();
					this._khid = value;
					this.SendPropertyChanged("khid");
					this.OnkhidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bdsid", DbType="Int NOT NULL")]
		public int bdsid
		{
			get
			{
				return this._bdsid;
			}
			set
			{
				if ((this._bdsid != value))
				{
					if (this._BatDongSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnbdsidChanging(value);
					this.SendPropertyChanging();
					this._bdsid = value;
					this.SendPropertyChanged("bdsid");
					this.OnbdsidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnid", DbType="Int NOT NULL")]
		public int cnid
		{
			get
			{
				return this._cnid;
			}
			set
			{
				if ((this._cnid != value))
				{
					if (this._HopDongChuyenNhuong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncnidChanging(value);
					this.SendPropertyChanging();
					this._cnid = value;
					this.SendPropertyChanged("cnid");
					this.OncnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylaphd", DbType="Date")]
		public System.Nullable<System.DateTime> ngaylaphd
		{
			get
			{
				return this._ngaylaphd;
			}
			set
			{
				if ((this._ngaylaphd != value))
				{
					this.OnngaylaphdChanging(value);
					this.SendPropertyChanging();
					this._ngaylaphd = value;
					this.SendPropertyChanged("ngaylaphd");
					this.OnngaylaphdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodot", DbType="Int")]
		public System.Nullable<int> sodot
		{
			get
			{
				return this._sodot;
			}
			set
			{
				if ((this._sodot != value))
				{
					this.OnsodotChanging(value);
					this.SendPropertyChanging();
					this._sodot = value;
					this.SendPropertyChanged("sodot");
					this.OnsodotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pttt", DbType="VarChar(50)")]
		public string pttt
		{
			get
			{
				return this._pttt;
			}
			set
			{
				if ((this._pttt != value))
				{
					this.OnptttChanging(value);
					this.SendPropertyChanging();
					this._pttt = value;
					this.SendPropertyChanged("pttt");
					this.OnptttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatri", DbType="Float")]
		public System.Nullable<double> giatri
		{
			get
			{
				return this._giatri;
			}
			set
			{
				if ((this._giatri != value))
				{
					this.OngiatriChanging(value);
					this.SendPropertyChanging();
					this._giatri = value;
					this.SendPropertyChanged("giatri");
					this.OngiatriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="Int")]
		public System.Nullable<int> tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BatDongSan_HopDongDatCoc", Storage="_BatDongSan", ThisKey="bdsid", OtherKey="bdsid", IsForeignKey=true)]
		public BatDongSan BatDongSan
		{
			get
			{
				return this._BatDongSan.Entity;
			}
			set
			{
				BatDongSan previousValue = this._BatDongSan.Entity;
				if (((previousValue != value) 
							|| (this._BatDongSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BatDongSan.Entity = null;
						previousValue.HopDongDatCocs.Remove(this);
					}
					this._BatDongSan.Entity = value;
					if ((value != null))
					{
						value.HopDongDatCocs.Add(this);
						this._bdsid = value.bdsid;
					}
					else
					{
						this._bdsid = default(int);
					}
					this.SendPropertyChanged("BatDongSan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDongChuyenNhuong_HopDongDatCoc", Storage="_HopDongChuyenNhuong", ThisKey="cnid", OtherKey="cnid", IsForeignKey=true)]
		public HopDongChuyenNhuong HopDongChuyenNhuong
		{
			get
			{
				return this._HopDongChuyenNhuong.Entity;
			}
			set
			{
				HopDongChuyenNhuong previousValue = this._HopDongChuyenNhuong.Entity;
				if (((previousValue != value) 
							|| (this._HopDongChuyenNhuong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDongChuyenNhuong.Entity = null;
						previousValue.HopDongDatCocs.Remove(this);
					}
					this._HopDongChuyenNhuong.Entity = value;
					if ((value != null))
					{
						value.HopDongDatCocs.Add(this);
						this._cnid = value.cnid;
					}
					else
					{
						this._cnid = default(int);
					}
					this.SendPropertyChanged("HopDongChuyenNhuong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HopDongDatCoc", Storage="_KhachHang", ThisKey="khid", OtherKey="khid", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HopDongDatCocs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HopDongDatCocs.Add(this);
						this._khid = value.khid;
					}
					else
					{
						this._khid = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HopDongDatCoc", Storage="_NhanVien", ThisKey="nvid", OtherKey="nvid", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HopDongDatCocs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HopDongDatCocs.Add(this);
						this._nvid = value.nvid;
					}
					else
					{
						this._nvid = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDongKyGui")]
	public partial class HopDongKyGui : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kgid;
		
		private int _nvid;
		
		private int _khid;
		
		private int _bdsid;
		
		private System.Nullable<double> _giatri;
		
		private System.Nullable<double> _chiphidv;
		
		private System.Nullable<System.DateTime> _ngaybd;
		
		private System.Nullable<System.DateTime> _ngaykt;
		
		private EntityRef<BatDongSan> _BatDongSan;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkgidChanging(int value);
    partial void OnkgidChanged();
    partial void OnnvidChanging(int value);
    partial void OnnvidChanged();
    partial void OnkhidChanging(int value);
    partial void OnkhidChanged();
    partial void OnbdsidChanging(int value);
    partial void OnbdsidChanged();
    partial void OngiatriChanging(System.Nullable<double> value);
    partial void OngiatriChanged();
    partial void OnchiphidvChanging(System.Nullable<double> value);
    partial void OnchiphidvChanged();
    partial void OnngaybdChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybdChanged();
    partial void OnngayktChanging(System.Nullable<System.DateTime> value);
    partial void OnngayktChanged();
    #endregion
		
		public HopDongKyGui()
		{
			this._BatDongSan = default(EntityRef<BatDongSan>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kgid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int kgid
		{
			get
			{
				return this._kgid;
			}
			set
			{
				if ((this._kgid != value))
				{
					this.OnkgidChanging(value);
					this.SendPropertyChanging();
					this._kgid = value;
					this.SendPropertyChanged("kgid");
					this.OnkgidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvid", DbType="Int NOT NULL")]
		public int nvid
		{
			get
			{
				return this._nvid;
			}
			set
			{
				if ((this._nvid != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnvidChanging(value);
					this.SendPropertyChanging();
					this._nvid = value;
					this.SendPropertyChanged("nvid");
					this.OnnvidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khid", DbType="Int NOT NULL")]
		public int khid
		{
			get
			{
				return this._khid;
			}
			set
			{
				if ((this._khid != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhidChanging(value);
					this.SendPropertyChanging();
					this._khid = value;
					this.SendPropertyChanged("khid");
					this.OnkhidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bdsid", DbType="Int NOT NULL")]
		public int bdsid
		{
			get
			{
				return this._bdsid;
			}
			set
			{
				if ((this._bdsid != value))
				{
					if (this._BatDongSan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnbdsidChanging(value);
					this.SendPropertyChanging();
					this._bdsid = value;
					this.SendPropertyChanged("bdsid");
					this.OnbdsidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatri", DbType="Float")]
		public System.Nullable<double> giatri
		{
			get
			{
				return this._giatri;
			}
			set
			{
				if ((this._giatri != value))
				{
					this.OngiatriChanging(value);
					this.SendPropertyChanging();
					this._giatri = value;
					this.SendPropertyChanged("giatri");
					this.OngiatriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiphidv", DbType="Float")]
		public System.Nullable<double> chiphidv
		{
			get
			{
				return this._chiphidv;
			}
			set
			{
				if ((this._chiphidv != value))
				{
					this.OnchiphidvChanging(value);
					this.SendPropertyChanging();
					this._chiphidv = value;
					this.SendPropertyChanged("chiphidv");
					this.OnchiphidvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybd", DbType="Date")]
		public System.Nullable<System.DateTime> ngaybd
		{
			get
			{
				return this._ngaybd;
			}
			set
			{
				if ((this._ngaybd != value))
				{
					this.OnngaybdChanging(value);
					this.SendPropertyChanging();
					this._ngaybd = value;
					this.SendPropertyChanged("ngaybd");
					this.OnngaybdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaykt", DbType="Date")]
		public System.Nullable<System.DateTime> ngaykt
		{
			get
			{
				return this._ngaykt;
			}
			set
			{
				if ((this._ngaykt != value))
				{
					this.OnngayktChanging(value);
					this.SendPropertyChanging();
					this._ngaykt = value;
					this.SendPropertyChanged("ngaykt");
					this.OnngayktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BatDongSan_HopDongKyGui", Storage="_BatDongSan", ThisKey="bdsid", OtherKey="bdsid", IsForeignKey=true)]
		public BatDongSan BatDongSan
		{
			get
			{
				return this._BatDongSan.Entity;
			}
			set
			{
				BatDongSan previousValue = this._BatDongSan.Entity;
				if (((previousValue != value) 
							|| (this._BatDongSan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BatDongSan.Entity = null;
						previousValue.HopDongKyGuis.Remove(this);
					}
					this._BatDongSan.Entity = value;
					if ((value != null))
					{
						value.HopDongKyGuis.Add(this);
						this._bdsid = value.bdsid;
					}
					else
					{
						this._bdsid = default(int);
					}
					this.SendPropertyChanged("BatDongSan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HopDongKyGui", Storage="_KhachHang", ThisKey="khid", OtherKey="khid", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HopDongKyGuis.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HopDongKyGuis.Add(this);
						this._khid = value.khid;
					}
					else
					{
						this._khid = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HopDongKyGui", Storage="_NhanVien", ThisKey="nvid", OtherKey="nvid", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HopDongKyGuis.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HopDongKyGuis.Add(this);
						this._nvid = value.nvid;
					}
					else
					{
						this._nvid = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _khid;
		
		private string _hoten;
		
		private string _diachi;
		
		private System.Nullable<int> _cmnd;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private System.Nullable<int> _sdt;
		
		private System.Nullable<bool> _gioitinh;
		
		private string _email;
		
		private System.Nullable<bool> _loaikh;
		
		private string _mota;
		
		private int _nvid;
		
		private EntitySet<BatDongSan> _BatDongSans;
		
		private EntitySet<YeuCauKhachHang> _YeuCauKhachHangs;
		
		private EntitySet<HopDongChuyenNhuong> _HopDongChuyenNhuongs;
		
		private EntitySet<HopDongDatCoc> _HopDongDatCocs;
		
		private EntitySet<HopDongKyGui> _HopDongKyGuis;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkhidChanging(int value);
    partial void OnkhidChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OncmndChanging(System.Nullable<int> value);
    partial void OncmndChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OnsdtChanging(System.Nullable<int> value);
    partial void OnsdtChanged();
    partial void OngioitinhChanging(System.Nullable<bool> value);
    partial void OngioitinhChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnloaikhChanging(System.Nullable<bool> value);
    partial void OnloaikhChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OnnvidChanging(int value);
    partial void OnnvidChanged();
    #endregion
		
		public KhachHang()
		{
			this._BatDongSans = new EntitySet<BatDongSan>(new Action<BatDongSan>(this.attach_BatDongSans), new Action<BatDongSan>(this.detach_BatDongSans));
			this._YeuCauKhachHangs = new EntitySet<YeuCauKhachHang>(new Action<YeuCauKhachHang>(this.attach_YeuCauKhachHangs), new Action<YeuCauKhachHang>(this.detach_YeuCauKhachHangs));
			this._HopDongChuyenNhuongs = new EntitySet<HopDongChuyenNhuong>(new Action<HopDongChuyenNhuong>(this.attach_HopDongChuyenNhuongs), new Action<HopDongChuyenNhuong>(this.detach_HopDongChuyenNhuongs));
			this._HopDongDatCocs = new EntitySet<HopDongDatCoc>(new Action<HopDongDatCoc>(this.attach_HopDongDatCocs), new Action<HopDongDatCoc>(this.detach_HopDongDatCocs));
			this._HopDongKyGuis = new EntitySet<HopDongKyGui>(new Action<HopDongKyGui>(this.attach_HopDongKyGuis), new Action<HopDongKyGui>(this.detach_HopDongKyGuis));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int khid
		{
			get
			{
				return this._khid;
			}
			set
			{
				if ((this._khid != value))
				{
					this.OnkhidChanging(value);
					this.SendPropertyChanging();
					this._khid = value;
					this.SendPropertyChanged("khid");
					this.OnkhidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="VarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="VarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="Int")]
		public System.Nullable<int> cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int")]
		public System.Nullable<int> sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit")]
		public System.Nullable<bool> gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaikh", DbType="Bit")]
		public System.Nullable<bool> loaikh
		{
			get
			{
				return this._loaikh;
			}
			set
			{
				if ((this._loaikh != value))
				{
					this.OnloaikhChanging(value);
					this.SendPropertyChanging();
					this._loaikh = value;
					this.SendPropertyChanged("loaikh");
					this.OnloaikhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="VarChar(100)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvid", DbType="Int NOT NULL")]
		public int nvid
		{
			get
			{
				return this._nvid;
			}
			set
			{
				if ((this._nvid != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnvidChanging(value);
					this.SendPropertyChanging();
					this._nvid = value;
					this.SendPropertyChanged("nvid");
					this.OnnvidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_BatDongSan", Storage="_BatDongSans", ThisKey="khid", OtherKey="khid")]
		public EntitySet<BatDongSan> BatDongSans
		{
			get
			{
				return this._BatDongSans;
			}
			set
			{
				this._BatDongSans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_YeuCauKhachHang", Storage="_YeuCauKhachHangs", ThisKey="khid", OtherKey="khid")]
		public EntitySet<YeuCauKhachHang> YeuCauKhachHangs
		{
			get
			{
				return this._YeuCauKhachHangs;
			}
			set
			{
				this._YeuCauKhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HopDongChuyenNhuong", Storage="_HopDongChuyenNhuongs", ThisKey="khid", OtherKey="khid")]
		public EntitySet<HopDongChuyenNhuong> HopDongChuyenNhuongs
		{
			get
			{
				return this._HopDongChuyenNhuongs;
			}
			set
			{
				this._HopDongChuyenNhuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HopDongDatCoc", Storage="_HopDongDatCocs", ThisKey="khid", OtherKey="khid")]
		public EntitySet<HopDongDatCoc> HopDongDatCocs
		{
			get
			{
				return this._HopDongDatCocs;
			}
			set
			{
				this._HopDongDatCocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HopDongKyGui", Storage="_HopDongKyGuis", ThisKey="khid", OtherKey="khid")]
		public EntitySet<HopDongKyGui> HopDongKyGuis
		{
			get
			{
				return this._HopDongKyGuis;
			}
			set
			{
				this._HopDongKyGuis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_KhachHang", Storage="_NhanVien", ThisKey="nvid", OtherKey="nvid", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.KhachHangs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.KhachHangs.Add(this);
						this._nvid = value.nvid;
					}
					else
					{
						this._nvid = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BatDongSans(BatDongSan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_BatDongSans(BatDongSan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_YeuCauKhachHangs(YeuCauKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_YeuCauKhachHangs(YeuCauKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_HopDongChuyenNhuongs(HopDongChuyenNhuong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HopDongChuyenNhuongs(HopDongChuyenNhuong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_HopDongDatCocs(HopDongDatCoc entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HopDongDatCocs(HopDongDatCoc entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_HopDongKyGuis(HopDongKyGui entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HopDongKyGuis(HopDongKyGui entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiBDS")]
	public partial class LoaiBD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _loaiid;
		
		private string _tenloai;
		
		private EntitySet<BatDongSan> _BatDongSans;
		
		private EntitySet<YeuCauKhachHang> _YeuCauKhachHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnloaiidChanging(int value);
    partial void OnloaiidChanged();
    partial void OntenloaiChanging(string value);
    partial void OntenloaiChanged();
    #endregion
		
		public LoaiBD()
		{
			this._BatDongSans = new EntitySet<BatDongSan>(new Action<BatDongSan>(this.attach_BatDongSans), new Action<BatDongSan>(this.detach_BatDongSans));
			this._YeuCauKhachHangs = new EntitySet<YeuCauKhachHang>(new Action<YeuCauKhachHang>(this.attach_YeuCauKhachHangs), new Action<YeuCauKhachHang>(this.detach_YeuCauKhachHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int loaiid
		{
			get
			{
				return this._loaiid;
			}
			set
			{
				if ((this._loaiid != value))
				{
					this.OnloaiidChanging(value);
					this.SendPropertyChanging();
					this._loaiid = value;
					this.SendPropertyChanged("loaiid");
					this.OnloaiidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloai", DbType="VarChar(20)")]
		public string tenloai
		{
			get
			{
				return this._tenloai;
			}
			set
			{
				if ((this._tenloai != value))
				{
					this.OntenloaiChanging(value);
					this.SendPropertyChanging();
					this._tenloai = value;
					this.SendPropertyChanged("tenloai");
					this.OntenloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiBD_BatDongSan", Storage="_BatDongSans", ThisKey="loaiid", OtherKey="loaiid")]
		public EntitySet<BatDongSan> BatDongSans
		{
			get
			{
				return this._BatDongSans;
			}
			set
			{
				this._BatDongSans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiBD_YeuCauKhachHang", Storage="_YeuCauKhachHangs", ThisKey="loaiid", OtherKey="loaiid")]
		public EntitySet<YeuCauKhachHang> YeuCauKhachHangs
		{
			get
			{
				return this._YeuCauKhachHangs;
			}
			set
			{
				this._YeuCauKhachHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BatDongSans(BatDongSan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiBD = this;
		}
		
		private void detach_BatDongSans(BatDongSan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiBD = null;
		}
		
		private void attach_YeuCauKhachHangs(YeuCauKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.LoaiBD = this;
		}
		
		private void detach_YeuCauKhachHangs(YeuCauKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.LoaiBD = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nvid;
		
		private string _taikhoan;
		
		private string _matkhau;
		
		private string _tennv;
		
		private System.Nullable<int> _sdt;
		
		private string _diachi;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private System.Nullable<bool> _gioitinh;
		
		private string _email;
		
		private System.Nullable<double> _doanhthu;
		
		private System.Nullable<bool> _quyen;
		
		private string _hinh;
		
		private EntitySet<YeuCauKhachHang> _YeuCauKhachHangs;
		
		private EntitySet<HopDongChuyenNhuong> _HopDongChuyenNhuongs;
		
		private EntitySet<HopDongDatCoc> _HopDongDatCocs;
		
		private EntitySet<HopDongKyGui> _HopDongKyGuis;
		
		private EntitySet<KhachHang> _KhachHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnvidChanging(int value);
    partial void OnnvidChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OntennvChanging(string value);
    partial void OntennvChanged();
    partial void OnsdtChanging(System.Nullable<int> value);
    partial void OnsdtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(System.Nullable<bool> value);
    partial void OngioitinhChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndoanhthuChanging(System.Nullable<double> value);
    partial void OndoanhthuChanged();
    partial void OnquyenChanging(System.Nullable<bool> value);
    partial void OnquyenChanged();
    partial void OnhinhChanging(string value);
    partial void OnhinhChanged();
    #endregion
		
		public NhanVien()
		{
			this._YeuCauKhachHangs = new EntitySet<YeuCauKhachHang>(new Action<YeuCauKhachHang>(this.attach_YeuCauKhachHangs), new Action<YeuCauKhachHang>(this.detach_YeuCauKhachHangs));
			this._HopDongChuyenNhuongs = new EntitySet<HopDongChuyenNhuong>(new Action<HopDongChuyenNhuong>(this.attach_HopDongChuyenNhuongs), new Action<HopDongChuyenNhuong>(this.detach_HopDongChuyenNhuongs));
			this._HopDongDatCocs = new EntitySet<HopDongDatCoc>(new Action<HopDongDatCoc>(this.attach_HopDongDatCocs), new Action<HopDongDatCoc>(this.detach_HopDongDatCocs));
			this._HopDongKyGuis = new EntitySet<HopDongKyGui>(new Action<HopDongKyGui>(this.attach_HopDongKyGuis), new Action<HopDongKyGui>(this.detach_HopDongKyGuis));
			this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nvid
		{
			get
			{
				return this._nvid;
			}
			set
			{
				if ((this._nvid != value))
				{
					this.OnnvidChanging(value);
					this.SendPropertyChanging();
					this._nvid = value;
					this.SendPropertyChanged("nvid");
					this.OnnvidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(50)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(50)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennv", DbType="NVarChar(100)")]
		public string tennv
		{
			get
			{
				return this._tennv;
			}
			set
			{
				if ((this._tennv != value))
				{
					this.OntennvChanging(value);
					this.SendPropertyChanging();
					this._tennv = value;
					this.SendPropertyChanged("tennv");
					this.OntennvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int")]
		public System.Nullable<int> sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(200)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit")]
		public System.Nullable<bool> gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanhthu", DbType="Float")]
		public System.Nullable<double> doanhthu
		{
			get
			{
				return this._doanhthu;
			}
			set
			{
				if ((this._doanhthu != value))
				{
					this.OndoanhthuChanging(value);
					this.SendPropertyChanging();
					this._doanhthu = value;
					this.SendPropertyChanged("doanhthu");
					this.OndoanhthuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen", DbType="Bit")]
		public System.Nullable<bool> quyen
		{
			get
			{
				return this._quyen;
			}
			set
			{
				if ((this._quyen != value))
				{
					this.OnquyenChanging(value);
					this.SendPropertyChanging();
					this._quyen = value;
					this.SendPropertyChanged("quyen");
					this.OnquyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh", DbType="NVarChar(250)")]
		public string hinh
		{
			get
			{
				return this._hinh;
			}
			set
			{
				if ((this._hinh != value))
				{
					this.OnhinhChanging(value);
					this.SendPropertyChanging();
					this._hinh = value;
					this.SendPropertyChanged("hinh");
					this.OnhinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_YeuCauKhachHang", Storage="_YeuCauKhachHangs", ThisKey="nvid", OtherKey="khid")]
		public EntitySet<YeuCauKhachHang> YeuCauKhachHangs
		{
			get
			{
				return this._YeuCauKhachHangs;
			}
			set
			{
				this._YeuCauKhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HopDongChuyenNhuong", Storage="_HopDongChuyenNhuongs", ThisKey="nvid", OtherKey="nvid")]
		public EntitySet<HopDongChuyenNhuong> HopDongChuyenNhuongs
		{
			get
			{
				return this._HopDongChuyenNhuongs;
			}
			set
			{
				this._HopDongChuyenNhuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HopDongDatCoc", Storage="_HopDongDatCocs", ThisKey="nvid", OtherKey="nvid")]
		public EntitySet<HopDongDatCoc> HopDongDatCocs
		{
			get
			{
				return this._HopDongDatCocs;
			}
			set
			{
				this._HopDongDatCocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HopDongKyGui", Storage="_HopDongKyGuis", ThisKey="nvid", OtherKey="nvid")]
		public EntitySet<HopDongKyGui> HopDongKyGuis
		{
			get
			{
				return this._HopDongKyGuis;
			}
			set
			{
				this._HopDongKyGuis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_KhachHang", Storage="_KhachHangs", ThisKey="nvid", OtherKey="nvid")]
		public EntitySet<KhachHang> KhachHangs
		{
			get
			{
				return this._KhachHangs;
			}
			set
			{
				this._KhachHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_YeuCauKhachHangs(YeuCauKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_YeuCauKhachHangs(YeuCauKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HopDongChuyenNhuongs(HopDongChuyenNhuong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HopDongChuyenNhuongs(HopDongChuyenNhuong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HopDongDatCocs(HopDongDatCoc entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HopDongDatCocs(HopDongDatCoc entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HopDongKyGuis(HopDongKyGui entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HopDongKyGuis(HopDongKyGui entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
}
#pragma warning restore 1591
